//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System;

[assembly: AssemblyTitle("Cake.Slack")]
[assembly: AssemblyDescription("Cake Slack AddIn")]
[assembly: AssemblyCompany("WCOM AB")]
[assembly: AssemblyProduct("Cake.Slack")]
[assembly: AssemblyVersion("0.9.0")]
[assembly: AssemblyFileVersion("0.9.0")]
[assembly: AssemblyInformationalVersion("0.9.0")]
[assembly: AssemblyCopyright("Copyright © WCOM AB 2018")]
[assembly: CLSCompliant(true)]

