//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System;

[assembly: AssemblyTitle("Cake.Slack")]
[assembly: AssemblyDescription("Cake Slack AddIn")]
[assembly: AssemblyCompany("WCOM AB")]
[assembly: AssemblyProduct("Cake.Slack")]
[assembly: AssemblyVersion("0.1.2")]
[assembly: AssemblyFileVersion("0.1.2")]
[assembly: AssemblyInformationalVersion("0.1.2")]
[assembly: AssemblyCopyright("Copyright © WCOM AB 2015")]
[assembly: CLSCompliant(true)]

